/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_playground;



public class App {
   
  

    public static void main(String[] args) {

        new Fibonacci();
        int input = 10;

        System.out.println(new App().getGreeting());
        
        //System.out.println(Fibonacci.FibMethod(input));
        
        //System.out.printf("FibNativeMethod: %d\n", Fibonacci.FibNativeMethod(input));

        //System.out.println("FibNativeMethodRecursion: " + Fibonacci.FibNativeMethodRecursion(input));
        
        System.out.println("FibMemo: " + Fibonacci.FibMemo(input));  
        }

    String getGreeting() {
        return "Hello World!";
    }

    public class StrategyDesignPattern {
    
    
        BasicCamera basicCamera;
        PlusCamera plusCamera;
   
}

}
